[applications.bash]
  version_command = "bash --version"
  version_regex = '''GNU bash, version (?P<version>[0-9.]+)'''

[applications.ruby]
  version_command = "ruby --version"
  version_regex = '''ruby (?P<version>[0-9.]+)'''

  eol = { product_name = "ruby", version_regex = '''.{3}''' }

[containers.ubuntu]
path = "ubuntu"
apps = [ "bash" ]

[containers.rubylang]
path = "rubylang/ruby"
apps = [ "bash", "ruby" ]