name: Release

on: [ push ]

jobs:
  build_release:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            toolchain: stable
            cross: false
            artifact_path: target/release/corrator
            artifact_name: corrator-macos
          - os: ubuntu-latest
            toolchain: stable
            cross: false
            artifact_path: target/release/corrator
            artifact_name: corrator-linux

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: --release --locked
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}
